### ISSUE TITLE
Nested Configuration via CLI

### ISSUE THREAD

**Issue by gbmarc1** [fidelity/spock#140]
**Describe the bug**
Cannot specify the value of a nested parameter via CLI. Unknow argument

**To Reproduce**
```
@spock
class TrainProcessConfig:
    """Common options for ax and train commands

    Attributes:
        cuda: Cuda device. If None, uses `CPU`.
        epochs: Maximum number of training epochs
        batch_size: Training batch size for gradient descent
    """

    cuda: Optional[int] = None
    epochs: int = 100
    batch_size: int = 32

@spock
class TrainConfig:
    """Options for train command

    Attributes:
        pw_scalar: Scalar that will multiply the pos_weights
        train_process: Training process configuration

    """

    pw_scalar: float = 1.0
    train_process: TrainProcessConfig = TrainProcessConfig()
```

**Expected behavior**

I am trying to execute the following configuration and overwrite the `epochs` argument with the cli. I am trying:

`train --TrainConfig.train_process.TrainProcessConfig.epochs 1`
or
`train --TrainConfig.train_process.epochs 1`

without any success what am I doing wrong?

I always get:
```
usage: train [-c CONFIG [CONFIG ...]] [-h]
[--TrainConfig.pw_scalar TRAINCONFIG.PW_SCALAR] 
[--TrainConfig.train_process TRAINCONFIG.TRAIN_PROCESS] 
train: error: unrecognized arguments: --TrainConfig.train_process.TrainProcessConfig.epochs
```
