### ISSUE TITLE
Printing help information to command line

### ISSUE THREAD

**Issue by dorukkilitcioglu** [fidelity/spock#38]
**Is your feature request related to a problem? Please describe.**
I want to be able to use the docstring of a class annotated with `@spock` to automatically show the relevant description of the variable when using the `--help` option from command line. This is similar to using the `help` parameter with `argparse`.

**Describe the solution you'd like**
Currently, an example information printed using the `--help` option looks like this:
```
USAGE:
  spock_test.py -c [--config] config1 [config2, config3, ...]
CONFIG:
  ModelConfig:
    n_features: int
    dropout: Optional[List[float]]
    hidden_sizes: Optional[Tuple[int]]
```

The new version could look like this, based on the docstring of the class:
```
USAGE:
  spock_test.py -c [--config] config1 [config2, config3, ...]
CONFIG:
  ModelConfig: (Configures a DNN model)
    n_features: int, the number of features
    dropout: Optional[List[float]], the amount of dropout
    hidden_sizes: Optional[Tuple[int]], the sizes of the hidden layers
```

As long as the user can see a description of the variables when using `--help`, the format doesn't matter.

**Describe alternatives you've considered**
None

**Additional context**
None
